package.json
src/Converters.ts
src/FunctionLoader.ts
test/FunctionLoaderTests.ts

Addresses issue: https://github.com/Azure/azure-functions-cli/issues/254
Reproduce steps
Configure a function for which the entry point doesn't return a function
e.g.: mistype module.exports and you'll end up with a valid entry point referencing an empty object
Proposed Solution
Improve the check and add a different message for when the entryPoint has been resolved but it is not a function

Improve FunctionLoader validations

---

protos/FunctionRpc.proto
src/Converters.ts
src/http/Request.ts

Adds raw body support to Node.js client
Requires host side improvements for https://github.com/Azure/azure-webjobs-sdk-script/issues/1951

Adds rawBody support

---

protos/FunctionRpc.proto
src/Converters.ts

Fixes an issue with the rawBody support for GET cases where it should be undefined (based on previous v1 behavior)

Change to use TypeData for rawbody (to allow for undefined)

---

azure-functions-language-worker-protobuf/README.md
azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto
src/Converters.ts

Updating headers to be string type, conversion handled on worker

---

src/Converters.ts
src/GrpcService.ts

Values of binding data shouldn't be null, but could be. This comes up in our runtime E2E test cases.
Also updating node version error message to be a bit more informative

Null check on bindingData value

---

src/GrpcService.ts

This PR improves the error message to avoid a situation like https://github.com/Azure/azure-functions-nodejs-worker/issues/89 this ever happening again.

👌 IMPROVE: Error Message

---

azure-functions-language-worker-protobuf/README.md
azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto
package-lock.json
package.json
package.ps1
src/Context.ts
src/Converters.ts
src/FunctionInfo.ts
src/FunctionLoader.ts
src/GrpcService.ts
src/Worker.ts
src/WorkerChannel.ts
src/http/Request.ts
test/ConvertersTests.ts
test/FunctionLoaderTests.ts
test/TestEventStream.ts
test/WorkerChannelTests.ts
tsconfig.json

Expands supported versions to be 8.x and 10.x
Note: test failures still need to be addressed when using v10.0.0 from this issue: https://github.com/nodejs/node/issues/20258
**Must consume latest proto file before pulling into functions-host: https://github.com/Azure/azure-functions-language-worker-protobuf/commit/a42a580e5211f89d5cc605a869a48425fccbd880**

NodeJs v10 support

---

src/Converters.ts

Resolves #98
Using node 10, nodejs worker shows this warning:
```
(node:11736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Upgrading from deprecated Buffer method

---

src/GrpcService.ts

Previously, we were going to deprecate node v8. Now, we are supporting Active LTS and Current versions.
Updating messaging to reflect decision. Resolves #107

Update node version warning message

---

src/Worker.ts
test/WorkerTests.ts

Helpful especially if there are azure-functions-host changes that result in missing or null worker start args.
REsolves #110

Better error message for wrong init node worker args

---

src/Converters.ts

This reverts commit 12cf5df767bf28bc2c43471188491f03a2acc9ee.
Resolves issue where byte array data was not being converted properly in functions host.

Revert "Upgrading from deprecated Buffer method (#103)"

---

Worker.nuspec
package-lock.json
package.json
src/Converters.ts
src/utils/Logger.ts

Resolves  #98 
Instead of doing `new Buffer(bytes: UInt8Array)`, we'll be doing `Buffer.from(bytes: UInt8Array)`
Note casting to "Buffer" type for node 8 typescript compilation purposes, but buffer.from(<UInt8Array>) has been supported since node v5

Removing things that cause buffer deprecation warnings

---

src/Converters.ts
test/ConvertersTests.ts

Parsing JavaScript array types leaves us with JSON objects that look like:
{ "0": "item 1", "1": "item 2" }
Resolves #125

Do not JSON.parse() array types

---

src/FunctionLoader.ts
test/FunctionLoaderTests.ts

Without added return the rejected async user function would cause an unhandled promise warning and failure to enact implicit call to context.done, which results in function timing out after 5 minutes.
@mhoeger This issue was introduced at https://github.com/Azure/azure-functions-nodejs-worker/commit/44410b6ae2cc9c786e887b2ff127c541cfc26476 when implementing `this` support for user functions.

Return a promise returned from a user function

---

package-lock.json
package.json
src/GrpcService.ts
src/Worker.ts
src/nodejsWorker.ts

Changing the node version warning to be very simple javascript in case very old version (v0.10.28) default is hit.
Resolves #128

Node version warning compatible down to v0

---

.gitignore
src/Context.ts
src/Converters.ts
src/WorkerChannel.ts
src/http/Request.ts
src/http/Response.ts
src/public/Interfaces.ts
test/ContextTests.ts
test/FunctionLoaderTests.ts
tsconfig.json
types/public/Interfaces.d.ts

This is step 1 to publishing typings. Idea is that `src/public/Interfaces` is the only file that will have typings generated from it and published ~~(either to @ types or as an npm package)~~ to @ types
Linked to https://github.com/Azure/azure-functions-nodejs-worker/issues/27

Refactor to isolate public interfaces

---

src/nodejsWorker.ts

When using a version of Node that is not an Active LTS or Current version (ex. 11.3.0), the runtime currently reports "Node.js version is too low." This can lead to logically inconsistent statements, ex.
`[error] Node.js version is too low. The version you are using is v11.3.0, but the runtime requires an Active LTS or Current version (ex: 8.11.1 or 10.60.)`
Reworded error message to be more generic.

Incompatible Node.js version error message fix.

---

appveyor.yml
setup-e2e-tests.ps1
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E.csproj
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Constants.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/CosmosDBEndToEndTests.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/EventHubsEndToEndTests.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Fixtures/FixtureHelpers.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Fixtures/FunctionAppFixture.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/HttpEndToEndTests.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/StorageEndToEndTests.cs

Per offline discussion, this refactoring:
- removes the need to write test output to .txt file
- isolates test environments, useful for tests that require specific settings

Refactored end-to-end tests to use xUnit's collection fixtures.

---

README.md
src/public/Interfaces.ts
test/InterfacesTest.ts
types/public/Interfaces.d.ts
types/public/package.json

Added contribution notes for TS too.
Expands on work done here (thanks @michael-watson !) https://github.com/Azure/azure-functions-nodejs-worker/pull/194

context.done should accept null as first param

---

azure-pipelines.yml

Bug in core tools, after v2.7.1382 Commit hash: f9f194023de4a35f29e07ff7d4c150e6650193f3
causes extension bundle download to fail.

Temporarily disable E2E tests

---

src/WorkerChannel.ts
src/augmenters/InvocationRequestAugmenters.ts
src/augmenters/index.ts
src/converters/BindingConverters.ts
test/BindingConvertersTests.ts
test/WorkerChannelTests.ts

Part of fix for #4735
Corresponding host PR
https://github.com/Azure/azure-functions-host/pull/4748
This needs to be merged before host PR goes in.

Account for removal of duplicate data from host

---

src/Context.ts
src/converters/RpcConverters.ts
src/public/Interfaces.ts
test/RpcConvertersTests.ts
types/public/Interfaces.d.ts

Part of fix for Azure/azure-functions-host#3747
Host PR: https://github.com/Azure/azure-functions-host/pull/4917
LanguageWorker PR: https://github.com/Azure/azure-functions-language-worker-protobuf/pull/40

Accept TraceContext from host

---

azure-pipelines.yml

This change adds v2,x as a branch to test. v2.x branch currently (see changes [here](https://github.com/Azure/azure-functions-nodejs-worker/compare/v2.x?expand=1)):
- removes Node.js v8
- changes worker version to 2.0.0
- introduces "v2Compatible" flag which reverts everything [breaking]
- [breaking] does not duplicate http payload in `context.bindingData`
- [breaking] fixes #228 (handles http output correctly on context.(null, { body: "hello" });
TODO:
- remove Node.js v10 support?
- potentially leverage Node.js v12 features
- [breaking] fix camelCase of timer trigger object: #188 
- potentially add to .proto
- [breaking] consider removing context.req and context.res objects: #204
- [breaking] in host and worker, make sure http payload "as raw" as possible
- explore options for bugs with …

Test v2.x branch

---

src/WorkerChannel.ts
src/converters/RpcHttpConverters.ts
test/RpcHttpConverters.ts

Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/268

Throw more helpful error if http output is incorrect

---

src/FunctionInfo.ts
src/WorkerChannel.ts
test/FunctionInfoTests.ts
test/WorkerChannelTests.ts

An orchestration trigger binding doesn't have a corresponding, explicit output, but does expect to be returned. This change returns that information in JSON form.

Fix durable-js in Azure Functions V3

---

azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto
azure-pipelines.yml
run-e2e-tests.ps1
src/converters/RpcHttpConverters.ts
src/public/Interfaces.ts
test/RpcHttpConverters.ts
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Helpers/CosmosDBHelpers.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Helpers/HttpHelpers.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/HttpEndToEndTests.cs
test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Utilities.cs
test/end-to-end/testFunctionApp/HttpTriggerSetsCookie/index.js
types/public/Interfaces.d.ts

Addresses https://github.com/Azure/azure-functions-host/issues/4890
Resolves https://github.com/Azure/azure-functions-host/issues/5384
Most of the changes in this PR is related to fixing the end to end tests to make more sense. RpcHttpConverters has the behavior-changing changes.

Add new SameSite property and tests

---

src/FunctionLoader.ts
test/FunctionLoaderTests.ts

Resolves https://github.com/Azure/azure-functions-host/issues/4809

Ignore proxy functions for loading

---

src/nodejsWorker.ts

Resolves https://github.com/Azure/azure-functions-core-tools/issues/1988 for Functions V2
Example output:
```
[error] Incompatible Node.js version (v6.11.1). The version of the Azure Functions runtime you are using (v2) supports Node.js v8.x and v10.x. Refer to our documentation to see the Node.js versions supported by each version of Azure Functions: https://aka.ms/functions-node-versions
```

Node.js version recommendation for V2

---

src/FunctionLoader.ts
test/FunctionLoaderTests.ts

* do not load proxy functions
* check against true
v2 version: https://github.com/Azure/azure-functions-nodejs-worker/pull/299/files

Ignore proxy functions in node worker v2.x
