Azure/azure-functions-nodejs-worker

- src/WorkerChannel.ts
fixed up merge issues with https://github.com/Azure/azure-functions-nodejs-worker/pull/44
> Avoid worker shutdown if function doesn't load

- src/Converters.ts
fixes https://github.com/Azure/azure-functions-nodejs-worker/issues/52
tests will be added in functions-host repo (since they are still there...)
> always return http as type for toRpcHttp

- src/WorkerChannel.ts
> Host crashes if >=1 function throws an exception on initialization

- src/GrpcService.ts
- src/Worker.ts
Send max send and receive message sizes on nodejs client, as done here: https://github.com/grpc/grpc/issues/8098
Resolves #60
> Set grpcMaxMessageLength on client

- package-lock.json
- src/GrpcService.ts
> Throw an informative if using unsupported version of node (not 8.x)

- src/Context.ts
- src/Converters.ts
- test/ContextTests.ts
- test/ConvertersTests.ts
> Recursively camelCase binding trigger metadata

- README.md
- package.ps1
- worker.config.json
> Add worker.config.json

- Worker.nuspec
- package-lock.json
- package.json
- package.ps1
Changes include:
- Node v10 support (note: node v8 will be deprecated in the near future)
- Debug tips with changing node version locally
Also, adding worker.config.json for use in https://github.com/Azure/azure-functions-host
> Update package version to beta3

- src/Context.ts
- src/WorkerChannel.ts
- test/ContextTests.ts
- test/ConvertersTests.ts
> Fix: Returning a promise and calling context.done results in an invalid message

- src/GrpcService.ts
- src/Worker.ts
- src/WorkerChannel.ts
- src/nodejsWorker.ts
- src/utils/Logger.ts
- webpack.config.js
LANGUAGE_WORKER_LOG is an arbitrary constant, could be changed.
> Add constant to filter internal logs

- package-lock.json
- src/FunctionLoader.ts
- test/FunctionLoaderTests.ts
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/37
For context, just porting over Matt's previously proposed changes from here: https://github.com/Azure/azure-functions-host/pull/1707/files
> Support 'this' in user code

- README.md
- appveyor.yml
- package-lock.json
- package.ps1
- webpack.config.js
Resolves #114
PowerShell doesn't automatically fail if an .exe the PowerShell script calls fails ([some context](https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error)). 
Solution is to error if any errors were found.
> Fail build if packaging step fails

- Worker.nuspec
- package-lock.json
- package.json
- src/nodejsWorker.ts
- src/utils/Logger.ts
Add [error] tag to system console errors
> Add [error] tag to console errors

- src/Context.ts
- src/Converters.ts
- test/ConvertersTests.ts
> Expose list of output bindings on the context object

- src/nodejsWorker.ts
New version of node available: https://github.com/Azure/app-service-announcements/issues/150
Changes in docs to here too: https://github.com/MicrosoftDocs/azure-docs-pr/pull/60139
> Recommend node v10.14.1

- .gitignore
- .vscode/launch.json
- Worker.nuspec
- package-lock.json
- package.json
- test/InterfacesTest.ts
- types/public/README.md
- types/public/package.json
This change adds a README and package.json.
The plan is to publish everything committed under `types/public`
Resolves #27
> NPM TypeScript type definitions

- README.md
- src/nodejsWorker.ts
This is in response to issue #164
> Clarified incompatible node version error message.

- types/public/README.md
- types/public/package.json
> Update @azure/functions readme

- package-lock.json
- src/Context.ts
- src/utils/Logger.ts
- test/ContextTests.ts
> Add check and log if context logging requested after execution completes

- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Fixtures/FixtureHelpers.cs
- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Fixtures/FunctionAppFixture.cs
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/190
> Log test function app console output

- src/Converters.ts
- src/http/Request.ts
- src/public/Interfaces.ts
- test/InterfacesTest.ts
- types/public/Interfaces.d.ts
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/193
> Http methods for TS

- appveyor.yml
- src/WorkerChannel.ts
- test/WorkerChannelTests.ts
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/174
> Update environment variables

- Worker.nuspec
- package-lock.json
- package.json
- src/FunctionInfo.ts
- src/WorkerChannel.ts
- types/public/package.json
https://github.com/Azure/azure-functions-nodejs-worker/issues/228
> Reverting context.done(null, res) fix to prevent breaking change

- src/WorkerChannel.ts
- src/converters/RpcHttpConverters.ts
- test/WorkerChannelTests.ts
- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/HttpEndToEndTests.cs
- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Utilities.cs
- test/end-to-end/testFunctionApp/HttpTriggerBodyAndRawBody/function.json
- test/end-to-end/testFunctionApp/HttpTriggerBodyAndRawBody/index.js
Part of fix for https://github.com/Azure/azure-functions-host/issues/3845
Do not merge until https://github.com/Azure/azure-functions-host/pull/4660 is merged.
> [Do not merge until corresponding host PR is merged] DuplicateBindingData Fixes

- package-lock.json
- src/Worker.ts
- src/utils/Logger.ts
> Log exception stack for uncaught exceptions

- azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto
- azure-pipelines.yml
- src/WorkerChannel.ts
- test/WorkerChannelTests.ts
> Re-setting working directory if given

- Worker.nuspec
- azure-pipelines.yml
- e2e-nightly-cli-azure-pipelines.yml
- e2e-nightly-site-azure-pipelines.yml
- package.json
- package.ps1
- scripts/generateProtos.js
- src/nodejsWorker.ts
- types/public/package.json
@ColbyTresness and @fabiocav - could you please review?
> Unblock Node.js v12 with appropriate warning

- package-lock.json
- package.json
- src/WorkerChannel.ts
- src/converters/RpcConverters.ts
- test/BindingConvertersTests.ts
- test/WorkerChannelTests.ts
> Add support for TypedDataCollections 

- Worker.nuspec
- azure-pipelines.yml
- e2e-nightly-cli-azure-pipelines.yml
- e2e-nightly-site-azure-pipelines.yml
- package-lock.json
- package.json
- src/WorkerChannel.ts
- test/WorkerChannelTests.ts
- types/public/package.json
Resolves https://github.com/Azure/azure-functions-nodejs-worker/issues/272
> Don't override all output binding data when return result present

- azure-pipelines.yml
- run-e2e-tests.ps1
- setup-e2e-tests.ps1
- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Fixtures/FunctionAppFixture.cs
- test/end-to-end/Azure.Functions.NodejsWorker.E2E/Azure.Functions.NodejsWorker.E2E/Helpers/CosmosDBHelpers.cs
Cosmos DB client wasn't correctly reading document. Root cause: https://github.com/MicrosoftDocs/azure-docs/issues/23792
Changing test to be against v3 host and allowing adding test result publish action
> test against host v3
